# Copyright (C) 2013 Google Inc., authors, and contributors <see AUTHORS file>
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>
# Created By: swizec@reciprocitylabs.com
# Maintained By: swizec@reciprocitylabs.comlanguage: python

python:
  - "2.7"
services: mysql
virtualenv:
  system_site_packages: true

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - "wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.17.zip  -nv"
  - "unzip -qd src google_appengine_1.9.17.zip"
  - "mv src/google_appengine/google src/"
  - "sudo pip install -r src/requirements.txt"
  - "sudo pip install -r src/dev-requirements.txt"
  - "sudo pip install google-api-python-client"
  - "sudo pip install mysql-python"
  - "sudo pip install webob"
  - 'gem install sass --version "=3.4.9"'
  - 'gem install compass --version "=1.0.1"'
 # weird travis-ci python paths
  - "export PYTHONPATH=$PYTHONPATH:/usr/lib/pymodules/python2.7/"
  - "export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages"
  - "export PYTHONPATH=$PYTHONPATH:/usr/lib/pyshared/python2.7/"
  - "export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/site-packages/"
  - npm install karma karma-jasmine jasmine-core phantomjs karma-chrome-launcher
before_script:
  - "source bin/init_env"
  - build_compass
  - build_assets
script:
  - bin/run_travis_tests
  - ./node_modules/karma/bin/karma start karma.conf.js --single-run
notifications:
  email: false
