language: python
python:
  - "2.7"
services: mysql
virtualenv:
  system_site_packages: true

install:
  - "wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.17.zip  -nv"
  - "unzip -qd src google_appengine_1.9.17.zip"
  - "mv src/google_appengine/google src/"
  - "pip install -r src/requirements.txt"
  - "pip install -r src/dev-requirements.txt"
  - "pip install hamlpy"
  - "pip install google-api-python-client"
  - "pip install mysql-python"
  - "pip install webob"
  - "pip install django"
before_script:
  - "source bin/init_env"
  # weird travis-ci python paths
  - "export PYTHONPATH=$PYTHONPATH:/usr/lib/pymodules/python2.7/"
  - "export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages"
  - "export PYTHONPATH=$PYTHONPATH:/usr/lib/pyshared/python2.7/"
  - "export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/site-packages/"
script:
  - bin/run_travis_tests
notifications:
  email: false
