---
ggrc_packages:
  - name: unzip
  - name: zip
  - name: make
  - name: python-virtualenv
  - name: fabric
  - name: python-mysqldb
  - name: python-imaging
  - name: sqlite3
  - name: python-dev
  - name: rubygems

ggrc_development_directories:
  - name: /vagrant-dev
  - name: /vagrant-dev/opt
  - name: /vagrant-dev/tmp
  - name: /vagrant/tmp

ggrc_gems:
  - name: sass
  - name: compass

ggrc_databases:
  - name: ggrcdev
  - name: ggrctest
